name: Lint/Test/Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-v2-
            ${{ runner.os }}

      - name: Install packages
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test --coverage

      - uses: codecov/codecov-action@v1
        with:
          verbose: true

      - name: Append current screenshot
        uses: peter-evans/commit-comment@v1
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          body: |
            ### 📷 Snapshot Tests

            | Previous UI | Current UI |
            | ----------- | ---------- |
            | ![Current snapshot](https://raw.githubusercontent.com/simonireilly/dynamoDB-benchworx/${{ github.event.pull_request.base.sha }}/cypress/snapshots/end-to-end/index.spec.tsx/latest.snap.png) | ![Current snapshot](https://raw.githubusercontent.com/simonireilly/dynamoDB-benchworx/${{ github.sha }}/cypress/snapshots/end-to-end/index.spec.tsx/latest.snap.png) |

            Changes to the UI that are applicable after this merge request.

      - name: Cypress
        run: yarn cy

      - uses: actions/upload-artifact@v1
        if: always() && (github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]')
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: always() && (github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]')
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Package Ubuntu
        run: yarn package
